/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nl.bioinf.vcftools;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.BasicParser;
import org.apache.commons.cli.ParseException;

/**
 *
 * @author aponnudurai
 */
public class Cli{

       public void parse(String[] args){
        
        Options opt = new Options();
        CommandLineParser parser = new BasicParser();
         opt.addOption("h","help",false, "Help function");
//         opt.addOption("<oneLetterOption>","<multipleLetterOption>",true,"description"); // true = can accept arguments, false = can not accept arguments
         opt.addOption("vcf", true, "this option defines the VCF file to be processed");
         opt.addOption("gvcf", true, "this option defines the compressed VCF file to be processed");
         opt.addOption("bcf", true, "this option defines the BCF file to be processed");
         opt.addOption("out", true, "this option defines the output filename prefix for all files generated by vcftools");
         opt.addOption("chr", true, "chromosome identifiers can be used more than once to include or exclude multiple chromosomes ");
         opt.addOption("from-bp",true, "this option defines the physical start position of site will be processed");
         opt.addOption("to-bp", true, "this option defines the physical stop position of site will be processed");
         opt.addOption("snp", true, "this option defines a snp which will be processed");
         opt.addOption("snps", true, "Include a list of SNPs given in a file, with one ID per line");
        
        try {
            
               CommandLine cmd = parser.parse(opt, args);
//               if(cmd.hasOption("")){
////               set setting values
//               }
               System.out.println(cmd.getOptionValue("chr"));
            
           
           
           } catch (ParseException ex) {
               System.out.println("Unexpected exception"+ex.getMessage());
           }


}
    
    
    
    
    
    
    
    
}
